remote_theme: cotes2020/jekyll-theme-chirpy
title: Dyskordia Velour Writing Desk of Chaos
description: Dancing on the Edge
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
